### ISSUE TITLE
Research and find good MPI libraries to use

### ISSUE THREAD

**Issue by rmcnew** [rmcnew/parallel_group_project#22]
Computing the Matrix Profile involves several mathematical and numerical operations on arrays of numbers.  Such operations include:
- Finding the length of the array of numbers
- Reversing an array of numbers
- Computing the mean of an array of numbers
- Computing the standard deviation for an array of numbers
- Computing the dot product between two arrays of numbers of equal length
- Computing the cross product between two arrays of number of equal length
- Computing Fast Fourier Transform for the array of numbers
- Computing Inverse Fast Fourier Transform for the array of numbers

These operations are commonly used in scientific applications and there are probably freely-available MPI libraries we can use to do these operations.  

We need to research to see what MPI-based scientific libraries are available and choose which ones to use in our project.

**Comment by rmcnew** [comment]
MPI libraries at Argonne National Laboratory:

https://www.mcs.anl.gov/research/projects/mpi/libraries/

**Comment by Brody-Larsen** [comment]
Most of these are "how-to tutorials" rather than libraries. However, I found a Fast Fourier Transform mpi library.

Finding the length of the array of numbers
	https://www.tutorialspoint.com/how-do-i-find-the-length-of-an-array-in-c-cplusplus

    Reversing an array of numbers
	https://www.tutorialspoint.com/reverse-an-array-in-cplusplus

    Computing the mean of an array of numbers
	https://www.geeksforgeeks.org/sum-of-an-array-using-mpi/
	https://mpitutorial.com/tutorials/mpi-reduce-and-allreduce/

    Computing the standard deviation for an array of numbers
	https://mpitutorial.com/tutorials/mpi-reduce-and-allreduce/


    Computing the dot product between two arrays of numbers of equal length
	???https://github.com/Amagnum/Parallel-Dot-Product-of-2-vectors-MPI/blob/main/main.cpp????


    Computing the cross product between two arrays of number of equal length
         couldn't find and MPI/parallel tutorial/library


    Computing Fast Fourier Transform for the array of numbers
	https://mpi4py-fft.readthedocs.io/en/latest/parallel.html

    Computing Inverse Fast Fourier Transform for the array of numbers
	???https://hal.archives-ouvertes.fr/hal-02088659/document???

**Comment by rmcnew** [comment]
We will incorporate these libraries in the next Sprint.
